### PR TITLE
Fix table parse bugs

### PR DESCRIPTION
**Pull request by coderfender**
The current table + schema parse bug fails as per the issue raised here.
This PR aims to fix those bugs and help users use SQLAlchemy layer on drill more effectively.
Also , I have tested these changes on my local machine / EC2 with superset queries

### CODE REVIEW

**Comment by JohnOmernik** [comment]
So this work may be in conflict with the work @cgivre  is doing to try to propagate the full schemas into super set with dots in it. It looks like the work is using extensions only, but with drill, you can select from a directory of csv, json, tsv, etc files and have it work, so relying only the extension may be problematic. @cgivre, what are your thoughts here?

**Comment by coderfender** [comment]
@JohnOmernik , I have added test cases for the each of the cases you mentioned above.Also , I tested the following scenarios in my personal  EC2 cluster
1) Select * from <file_name.extension> ( Works)
2) Select * from namespace.schema.folder (Works)
3) Select * from namespace.schema.folder.file.extension (Works)
4) Select * from table_name (Works)

Also , this change would be more on a query side to populate the data. Also , this change would fix the issue in SQL lab and chart building UIs. 

@JohnOmernik , @cgivre , Let me know what you think . If you think this change will be conflicting, then I can go ahead make changes to better integrate the changes

**Comment by JohnOmernik** [comment]
So, I want @cgirve to look at things for sure. 

The sadrill.py removal of 
   if "@@@" in table_name:
            table_name = table_name.replace("@@@", ".")

I think would hurt what he's trying to do with better Superset integration. So let's wait for his comment. 

Another test to add that I know works in Drill is

select * from namespace.schema.folder/*.extension

**Comment by cgivre** [comment]
@JohnOmernik 
There was a recent PR in Superset (https://github.com/apache/incubator-superset/pull/7453) which eliminates the need for the `@@@` code, so we are safe to remove that from the dialect.  I need to test the other features and will do so this weekend.

**Comment by coderfender** [comment]
@JohnOmernik , I will try to test select * from namespace.schema.folder/*.extension and update here

**Comment by coderfender** [comment]
I added a test case for the query you mentioned @JohnOmernik .

**Comment by coderfender** [comment]
Hello Guys, do you think I need to make further changes to the PR  or is it okay to merge ?

**Comment by JohnOmernik** [comment]
I just merged @cgivre latest.  Do we still have issues or are we safe now with the updates in Superset?

**Comment by cgivre** [comment]
Superset is working very well with the dialect and the REST interface.  I've not tested it extensively with JDBC, but I will do so this week, so look for some additional updates. 

Once JDBC is sorted out, I'd like to push this whoe thing to Pypi/Conda for ease of installation.

-- C

**Comment by coderfender** [comment]
So you guys think that this PR is no longer needed ?

**Comment by cgivre** [comment]
Is this PR still needed?  I just pushed a change that fixes view handling.  IMHO, this dialect is pretty solid.

**Comment by coderfender** [comment]
No I think we can safely close this PR now that the issue is fixed on the Superset side

**Comment by cgivre** [comment]
Do you want to close this PR?  Not sure that it is relevant anymore.

**Comment by coderfender** [comment]
Closing the PR. I guess its not needed anymore

**Pull request closed without merging**
